export const FETCH_CUSTOMER_DETAILS = "FETCH_CUSTOMER_DETAILS"
export const FETCH_CUSTOMER_DETAILS_SUCCESS = "FETCH_CUSTOMER_DETAILS_SUCCESS"
export const FETCH_CUSTOMER_DETAILS_FAILURE = "FETCH_CUSTOMER_DETAILS_FAILURE"
export const FETCH_CUSTOMER_DETAILS_INIT = "FETCH_CUSTOMER_DETAILS_INIT"


export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS"
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE"
export const UPDATE_USER_DETAILS_INIT = "UPDATE_USER_DETAILS_INIT"


export const CREATE_USER = "CREATE_USER"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"
export const CREATE_USER_INIT = "CREATE_USER_INIT"